  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./:/home/node"
