  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    env_file:
      - .env
    environment:
      DOCUMENTROOT: ${DOCUMENTROOT:-public}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
