  postgres:
    build:
      context: docker/postgres
      dockerfile: src/trechos/dockerfile/postgres/Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    env_file:
      - .env
